### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by ingageco** [hairyhenderson/node-fellowshipone#37]
@hairyhenderson  - Have you considered retooling the lib to use Promises? I'm considering a fork to make this happen using Q.

**Comment by hairyhenderson** [comment]
@ingageco - I hadn't considered it, but I'm not opposed to it. Is Q the best approach? There's native [Promise](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) support in JavaScript now, which is supported in Node.js 4 & 5. I'd much rather use the runtime support rather than add a dependency...

But, it _would_ mean dropping support for Node.js 0.10/0.12, which I'm not opposed to, but not _quite_ ready to do :)

Which version of Node are you using?

**Comment by hairyhenderson** [comment]
So I've been working on this a bit, and I've hit a snag...

Promises can only resolve a single value, so functions like `F1.get_token`, which yields two (`creds`, `url`), won't work as-is.

After looking through the project I think `get_token` is the only offender, so it might be legit to just deprecate that function (at least for Promise-based use).

**Comment by ingageco** [comment]
Hey Davy - looks great. Unfortunately, the office staff at the church is so bent on leaving F1 that I've not worked much with it. They're looking to close the deal on a new system very soon, so I've decided to put my efforts into other areas. To be honest, I'm disappointed - you've done the best work here that Ive seen for integrating with the F1 api and I was hoping to get to work with you on it.

**Comment by hairyhenderson** [comment]
@ingageco - lol. Actually, we're looking at alternatives too - out of curiosity, what system is your church switching to?

The reason I started writing this library initially was to try and ease some frustrations that my church was having with F1's interface... It's a common theme with F1 users, I think :wink:

**Comment by ingageco** [comment]
They're looking at a newer company called Seraphim - can you connect via email? jay [at] weingage.com

**Comment by hairyhenderson** [comment]
e-mail sent :smile:

**Comment by hairyhenderson** [comment]
Won't be implementing this - we're not using F1 anymore...
